#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xam.Plugins.DragLayout.Resource", IsApplication=false)]

namespace Xam.Plugins.DragLayout
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public static int layout_layer = 2130771968;
			
			// aapt resource value: 0x7F010001
			public static int maxScrollTime = 2130771969;
			
			// aapt resource value: 0x7F010002
			public static int overScroll = 2130771970;
			
			// aapt resource value: 0x7F010003
			public static int scrollVelocity = 2130771971;
			
			// aapt resource value: 0x7F010004
			public static int touchScrollable = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public static int all = 2130837504;
			
			// aapt resource value: 0x7F020001
			public static int bottom = 2130837505;
			
			// aapt resource value: 0x7F020002
			public static int center = 2130837506;
			
			// aapt resource value: 0x7F020003
			public static int left = 2130837507;
			
			// aapt resource value: 0x7F020004
			public static int none = 2130837508;
			
			// aapt resource value: 0x7F020005
			public static int right = 2130837509;
			
			// aapt resource value: 0x7F020006
			public static int top = 2130837510;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F030000
			public static int app_name = 2130903040;
			
			// aapt resource value: 0x7F030001
			public static int hello = 2130903041;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010001,0x7F010002,0x7F010003,0x7F010004 }
			public static int[] DragLayout = new int[] {
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: { 0x10100B3,0x7F010000 }
			public static int[] DragLayout_Layout = new int[] {
					16842931,
					2130771968};
			
			// aapt resource value: 0
			public static int DragLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 1
			public static int DragLayout_Layout_layout_layer = 1;
			
			// aapt resource value: 0
			public static int DragLayout_maxScrollTime = 0;
			
			// aapt resource value: 1
			public static int DragLayout_overScroll = 1;
			
			// aapt resource value: 2
			public static int DragLayout_scrollVelocity = 2;
			
			// aapt resource value: 3
			public static int DragLayout_touchScrollable = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
